<template>
     <div class="card">
              <img src="https://m.media-amazon.com/images/I/719tCHXNiXL._AC_UL320_.jpg">
              <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text"></p><p>
                  
                </p>
                <a href="#" class="btn btn-primary">Buy</a>
              </div>
            </div>
</template>
